// <auto-generated />
using System;
using FlightSchedule.EntityBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightSchedule.EntityBase.Migrations
{
    [DbContext(typeof(FlightScheduleDbContext))]
    partial class FlightScheduleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightSchedule.EntityBase.Entity.Flight", b =>
                {
                    b.Property<long>("FlightId")
                        .HasColumnType("bigint");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId")
                        .HasDatabaseName("idx_flight_airline_id");

                    b.HasIndex("DepartureTime")
                        .HasDatabaseName("idx_flight_departure_time");

                    b.HasIndex("RouteId");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("FlightSchedule.EntityBase.Entity.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("int");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("int");

                    b.HasKey("RouteId");

                    b.HasIndex("DepartureDate")
                        .HasDatabaseName("idx_route_departure_date");

                    b.HasIndex("OriginCityId", "DestinationCityId", "DepartureDate")
                        .IsUnique();

                    b.ToTable("Route");
                });

            modelBuilder.Entity("FlightSchedule.EntityBase.Entity.Subscription", b =>
                {
                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("int");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("int");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("idx_subscription_agency_id");

                    b.HasIndex("DestinationCityId")
                        .HasDatabaseName("idx_subscription_destination_city_id");

                    b.HasIndex("OriginCityId")
                        .HasDatabaseName("idx_subscription_origin_city_id");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("FlightSchedule.EntityBase.Entity.Flight", b =>
                {
                    b.HasOne("FlightSchedule.EntityBase.Entity.Route", "Route")
                        .WithMany("Flights")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("FlightSchedule.EntityBase.Entity.Route", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
